### ISSUE TITLE
NoSuchJobException

### ISSUE THREAD

**Issue by amoscatelli** [jberet/jsr352#105]
We have a WAR containing jberet-ui + jberet-rest (plus dependencies, as you can see in the attached pom) resources exposed with a REST application (by annotation). JBeret-UI API url points to the very war itself (because the war itself exposes the rest resources as already said).

Then we have an EAR containing the previous defined WAR and an EJB module (among other things) containing some Batchlets. 

In summary : we are sure we have jberet-ui pointing to jberet-rest apis exposed in a war inside an ear with several batchlet.

Then we try to start some of these batchlet using jberet-ui and this actually works (the job starts and works without problem but an error is print in log and is shown in the user interface, screenshot attached) :

> 2018-01-08 15:01:13,441 WARN  [org.jberet.rest-api] (default task-45) JBERET071000: Exception occurred when accessing JBeret Rest API:: javax.batch.operations.NoSuchJobException: WFLYBATCH000005: The job name 'importTreatmentCsv' was not found for the deployment.
        at org.wildfly.extension.batch.jberet.deployment.JobOperatorService.validateJob(JobOperatorService.java:404)
        at org.wildfly.extension.batch.jberet.deployment.JobOperatorService.getJobInstance(JobOperatorService.java:282)
        at org.wildfly.extension.batch.jberet.deployment.JobOperatorService.getJobExecution(JobOperatorService.java:308)
        at org.jberet.operations.DelegatingJobOperator.getJobExecution(DelegatingJobOperator.java:97)
        at org.jberet.rest.service.JobService.start(JobService.java:60)
        at org.jberet.rest.resource.JobResource.start(JobResource.java:72)
        at org.jberet.rest.resource.JobResource$Proxy$_$$_WeldClientProxy.start(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:406)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:213)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:209)
        at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:244)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:209)
        at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:244)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.security.jaspi.JASPICSecureResponseHandler.handleRequest(JASPICSecureResponseHandler.java:48)
        at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:326)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:812)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

> 2018-01-08 15:01:13,688 INFO  [org.visiontech.batch.AbstractImportEntityBatchlet] (Batch Thread - 2) COMPLETED

As you can see at the end of the log the job actually worked and completed.

Something is not right, obliviously.
The UI itself can't refresh showing the jobs ...

I think this bug may be related to both rest rest-api and ui.

Can you help us ?

![image](https://user-images.githubusercontent.com/16684470/34676683-f2941dd6-f48d-11e7-8415-90f91057cd34.png)
[pom.zip](https://github.com/jberet/jsr352/files/1611947/pom.zip)

**Comment by jamezp** [comment]
What version of WildFly are you using?

**Comment by amoscatelli** [comment]
I am sorry, I totally forgot to mention the environment.

JDK 8 (CentOS 7)
Wildfly 11 Final + Jberet 1.3.0 Beta 7 (core, rest, ui)

**Comment by amoscatelli** [comment]
extra info :  

I created a custom JBeret module (under modules folder) to override older default jboss jberet release.

**Comment by jamezp** [comment]
Where is the `importTreatmentCsv.xml` located? This is likely due to the way WildFly sees available jobs. I'd have to try to come up with a reproducer so I can see what is happening.

**Comment by amoscatelli** [comment]
I added a couple of screenshot to make this clearer

![image](https://user-images.githubusercontent.com/16684470/34679336-eb226104-f495-11e7-80f7-42879bc27193.png)

![image](https://user-images.githubusercontent.com/16684470/34679380-0dcd0a4c-f496-11e7-84a8-40bf9eac79cd.png)

**Comment by jamezp** [comment]
Can you execute the following CLI command and paste the results here?
```
/deployment=optoplus-services-ear-1.0.18-SNAPSHOT.ear/subdeployment=jberet-ui-mvn-1.0.0-SNAPSHOT.war/subsystem=batch-jberet:read-attribute(name=job-xml-names)
```

**Comment by amoscatelli** [comment]
{
    "outcome" => "success",
    "result" => [
        "importTreatmentCsv.xml",
        "importLenseCsv.xml",
        "importContactLensCsv.xml",
        "importMaterialCsv.xml",
        "initData.xml"
    ]
}

**Comment by jamezp** [comment]
This looks like an issue in WildFly. See https://issues.jboss.org/browse/WFLY-9658.
