### ISSUE TITLE
Annotation Exception for Rest API

### ISSUE THREAD

**Issue by remmeier** [jberet/jsr352#75]
I'm using wildfly 10 with the most recent jberet beta, I guess the XMLTransient needs to be removed?

Caused by: com.sun.xml.bind.v2.runtime.IllegalAnnotationsException: 1 counts of IllegalAnnotationExceptions
Transient field "future" cannot have any JAXB annotations.
	this problem is related to the following location:
		at @javax.xml.bind.annotation.XmlTransient()
		at org.jberet.schedule.JobSchedule

	at com.sun.xml.bind.v2.runtime.IllegalAnnotationsException$Builder.check(IllegalAnnotationsException.java:106)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:460)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:292)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:139)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1138)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:211)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:392)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:618)
	at org.jboss.resteasy.plugins.providers.jaxb.JAXBContextWrapper.<init>(JAXBContextWrapper.java:88)
	at org.jboss.resteasy.plugins.providers.jaxb.JAXBContextWrapper.<init>(JAXBContextWrapper.java:113)
	at org.jboss.resteasy.plugins.providers.jaxb.XmlJAXBContextFinder.createContextObject(XmlJAXBContextFinder.java:56)
	at org.jboss.resteasy.plugins.providers.jaxb.AbstractJAXBContextFinder.createContext(AbstractJAXBContextFinder.java:150)
	at org.jboss.resteasy.plugins.providers.jaxb.XmlJAXBContextFinder.findCacheContext(XmlJAXBContextFinder.java:72)
	at org.jboss.resteasy.plugins.providers.jaxb.CollectionProvider.writeTo(CollectionProvider.java:298)
	... 42 more

**Comment by chengfang** [comment]
Thanks for reporting the issue.  Yes, we should remove @XmlTransient from 'future' field, which is already marked as transient.

The check is performed by com/sun/xml/bind/v2/model/impl/ClassInfoImpl
https://github.com/gf-metro/jaxb/blob/master/jaxb-ri/runtime/impl/src/main/java/com/sun/xml/bind/v2/model/impl/ClassInfoImpl.java#L372

**Comment by chengfang** [comment]
This error occurs when XML media type is used.  JSON media type should work fine.

**Comment by chengfang** [comment]
The fix will be included in the next release (1.3.0.Beta3).
